from 4 spaces to tab

diff --git a/nettygear/nettygear b/nettygear/nettygear
--- a/nettygear/nettygear
+++ b/nettygear/nettygear
@@ -8,172 +8,172 @@
 #export $(cat /proc/$(pgrep -u `whoami` ^gnome-shell$)/environ | grep -z DBUS_SESSION_BUS_ADDRESS)
 
 #TODO: move functions to another file
-########################################
-#             FUNCTIONS                #
-########################################
+#########################################
+#				 FUNCTIONS
+#########################################
 
 function showHelp () {
-    if [[ ! -z "$GUI" ]]; then
-        notify-send -i $IC_HELP "Usage:" "nettygear   [ -g ]  [ r, n, d, i, h, a, c ]   [ -l ]"
-        exit 0
-    fi
+	if [[ ! -z "$GUI" ]]; then
+		notify-send -i $IC_HELP "Usage:" "nettygear   [ -g ]  [ r, n, d, i, h, a, c ]   [ -l ]"
+		exit 0
+	fi
 
-    echo -e "Usage: nettygear [ -g ] {[OPTION] | [ -l ]}
-    -g   \tenable gui [requires libnotify\zenity]
+	echo -e "Usage: nettygear [ -g ] {[OPTION] | [ -l ]}
+	-g   \tenable gui [requires libnotify\zenity]
 
-    -r,  \treboot router
-    -n,  \tchange current IP
-    -d,  \tshow current downstream speed
-    -i,  \tshow current external IP address
-    -h,  \thelp info
-    -a,  \tset new authentication
-    -c,  \tclear configuration
+	-r,  \treboot router
+	-n,  \tchange current IP
+	-d,  \tshow current downstream speed
+	-i,  \tshow current external IP address
+	-h,  \thelp info
+	-a,  \tset new authentication
+	-c,  \tclear configuration
 
-    -l   \tstart with graphical list [requires libnotify\zenity]"
+	-l   \tstart with graphical list [requires libnotify\zenity]"
 }
 
 # $1 icon;  $2 bold;  $3 message;
 function notify () {
-    if [[ "$GUI" == "true" ]]; then
-        notify-send -i "$1" "$2" "$3"
-    else
-        echo -e "\033[1m$2 \e[0m$3\n"
-    fi
+	if [[ "$GUI" == "true" ]]; then
+		notify-send -i "$1" "$2" "$3"
+	else
+		echo -e "\033[1m$2 \e[0m$3\n"
+	fi
 }
 
 # $1 page\todo;  $2 print curl output;   2 seconds timeout
 function executeURL () {
-    #OUT="`curl -m 2 -s -u $U:$P $HOST/$1`"          #no auth
-    #OUT="`curl -m 2 -s -u $U:$P -digest $HOST/$1`"  #auth correct, params not used
-    OUT="`wget --http-user=$U --http-password=$P -q -O - "$HOST/$1"`"
-    if [[ "$2" == "print" ]]; then
-        echo "$OUT"
-    fi
+	#OUT="`curl -m 2 -s -u $U:$P $HOST/$1`"				#no auth
+	#OUT="`curl -m 2 -s -u $U:$P -digest $HOST/$1`"		#auth correct, params not used
+	OUT="`wget --http-user=$U --http-password=$P -q -O - "$HOST/$1"`"
+	if [[ "$2" == "print" ]]; then
+		echo "$OUT"
+	fi
 }
 
 function rebootRouter() {
-    notify $IC_NET "Rebooting!" "This will take a while... "
-    executeURL $REBOOT
-    while [ -z `getIP` ]; do
-        sleep 1
-        let TIME++
-        echo -ne "$TIME"'\r';
-    done
+	notify $IC_NET "Rebooting!" "This will take a while... "
+	executeURL $REBOOT
+	while [ -z `getIP` ]; do
+		sleep 1
+		let TIME++
+		echo -ne "$TIME"'\r';
+	done
 
-    notify $IC_NET "Online" "in $TIME seconds\n"
-    executeURL " " #needed for auth
-    showIP
-    showDLspeed
+	notify $IC_NET "Online" "in $TIME seconds\n"
+	executeURL " " #needed for auth
+	showIP
+	showDLspeed
 }
 
 # 10 seconds timeout
 function getIP() {
-    echo "`curl -m 10 -s "http://checkip.amazonaws.com"`"
+	echo "`curl -m 10 -s "http://checkip.amazonaws.com"`"
 }
 
 function showIP() {
-    IP=`getIP`
+	IP=`getIP`
 
-    if [[ -z "$IP" ]]; then
-        IP="0.0.0.0"
-    fi
+	if [[ -z "$IP" ]]; then
+		IP="0.0.0.0"
+	fi
 
-    notify $IC_CHECK "IP address:" $IP
+	notify $IC_CHECK "IP address:" $IP
 }
 
 function newIP() {
-    notify $IC_NET "Changing IP address!" "This will take a few seconds..."
-    echo "disconnecting..."
-    executeURL $DISCONNECT
-    echo "connecting..."
-    executeURL $CONNECT
-    showIP
+	notify $IC_NET "Changing IP address!" "This will take a few seconds..."
+	echo "disconnecting..."
+	executeURL $DISCONNECT
+	echo "connecting..."
+	executeURL $CONNECT
+	showIP
 }
 
 function showDLspeed() {
-    OUT=`executeURL $STATS "print"`
+	OUT=`executeURL $STATS "print"`
 
-    #get extract speed
-    LINE=`echo "$OUT" | grep kbps | head -n 1`
-    DLSPEED=`echo $LINE | cut -d '>' -f 3 | cut -d ' ' -f 1`
+	#get extract speed
+	LINE=`echo "$OUT" | grep kbps | head -n 1`
+	DLSPEED=`echo $LINE | cut -d '>' -f 3 | cut -d ' ' -f 1`
 
-    if [[ -z "$DLSPEED" ]]; then
-        DLSPEED="0"
-    fi
+	if [[ -z "$DLSPEED" ]]; then
+		DLSPEED="0"
+	fi
 
-    notify $IC_MONITOR "Downstream:" "$DLSPEED kbps"
+	notify $IC_MONITOR "Downstream:" "$DLSPEED kbps"
 }
 
 
 function showListGUI() {
-    if [[ -z `which zenity 2> /dev/null` ]]; then
-        notify $IC_NET "Dependency issue:" "zenity not found"
-        exit 2
-    fi
+	if [[ -z `which zenity 2> /dev/null` ]]; then
+		notify $IC_NET "Dependency issue:" "zenity not found"
+		exit 2
+	fi
 
-    GUI=true
+	GUI=true
 
-    opt1="Reboot"
-    opt2="Show Net IP"
-    opt3="Change IP"
-    opt4="Show DL Speed"
-    opt5="Set Autenticazione"
-    opt6="Clear Configuration"
+	opt1="Reboot"
+	opt2="Show Net IP"
+	opt3="Change IP"
+	opt4="Show DL Speed"
+	opt5="Set Autenticazione"
+	opt6="Clear Configuration"
 
-    op=`zenity --name="nettygear" --window-icon="$IC_NET" --height=245 --list --radiolist --title="Netty Gear" \
-    --text 'Select operation:' \
-    --column '' \
-    --column 'Operation' FALSE "$opt1" FALSE "$opt2" FALSE "$opt3" FALSE "$opt4" FALSE "$opt5" FALSE "$opt6"`
+	op=`zenity --name="nettygear" --window-icon="$IC_NET" --height=245 --list --radiolist --title="Netty Gear" \
+	--text 'Select operation:' \
+	--column '' \
+	--column 'Operation' FALSE "$opt1" FALSE "$opt2" FALSE "$opt3" FALSE "$opt4" FALSE "$opt5" FALSE "$opt6"`
 
-    case "$op" in
-        $opt1)
-            rebootRouter
-        ;;
-        $opt2)
-            showIP
-        ;;
-        $opt3)
-            newIP
-        ;;
-        $opt4)
-            showDLspeed
-        ;;
-        $opt5)
-            setAuthentication
-        ;;
-        $opt6)
-            clearConfiguration "force"
-        ;;
-    esac
+	case "$op" in
+		$opt1)
+			rebootRouter
+		;;
+		$opt2)
+			showIP
+		;;
+		$opt3)
+			newIP
+		;;
+		$opt4)
+			showDLspeed
+		;;
+		$opt5)
+			setAuthentication
+		;;
+		$opt6)
+			clearConfiguration "force"
+		;;
+	esac
 }
 
 function setAuthentication() {
-    if [[ -z "$U" || -z "$P" || "$1" == "force" ]];then
-        if [[ "$GUI" == "true" ]];then
-            SET=`zenity --name="nettygear" --window-icon="$IC_NET" --title="Netty Gear" --password --username`
-            U=`echo "$SET" |  cut -d '|' -f 1`
-            P=`echo "$SET" |  cut -d '|' -f 2`
-        else
-            echo -n "Enter Username: "
-            read U
-            echo -n "Enter Password: "
-            read P
-        fi
-        echo "USER=$U" > $CONF
-        echo "PASS=$P" >> $CONF
-        echo -e "Username & Password saved in $CONF\n"
-    fi
+	if [[ -z "$U" || -z "$P" || "$1" == "force" ]];then
+		if [[ "$GUI" == "true" ]];then
+			SET=`zenity --name="nettygear" --window-icon="$IC_NET" --title="Netty Gear" --password --username`
+			U=`echo "$SET" |  cut -d '|' -f 1`
+			P=`echo "$SET" |  cut -d '|' -f 2`
+		else
+			echo -n "Enter Username: "
+			read U
+			echo -n "Enter Password: "
+			read P
+		fi
+		echo "USER=$U" > $CONF
+		echo "PASS=$P" >> $CONF
+		echo -e "Username & Password saved in $CONF\n"
+	fi
 }
 
 
 function clearConfiguration() {
-    rm "$CONF" 2> /dev/null
-    notify $IC_REMOVE "Configuration cleared."
+	rm "$CONF" 2> /dev/null
+	notify $IC_REMOVE "Configuration cleared."
 }
 
-########################################
-#             PARAMETERS               #
-########################################
+#########################################
+#				PARAMETERS
+#########################################
 
 # parameters
 CONF=$HOME/.config/nettygear.conf
@@ -188,36 +188,36 @@ CONNECT="cgi-bin/RST_conn_status.asp?connect_status&Saveflag=1&DipConnFlag=1&Sav
 STATS="cgi-bin/RST_statistic.asp"
 
 # icons
-IC_HELP=gnome-help                 #for printHelp gui
-IC_NET=preferences-system-network  #for rebooting info
-IC_MONITOR=gnome-monitor           #downspeed success
-IC_NET_ERROR=network-error         #reboot\downspeed error
-IC_NET_TOOL=gnome-nettool          #myip
-IC_CHECK=checkbox                  #newip success
-IC_ERROR=error                     #wrong arguments, login error
-IC_REMOVE=gtk-remove               #remove configuration
+IC_HELP=gnome-help					#for printHelp gui
+IC_NET=preferences-system-network	#for rebooting info
+IC_MONITOR=gnome-monitor			#downspeed success
+IC_NET_ERROR=network-error			#reboot\downspeed error
+IC_NET_TOOL=gnome-nettool			#myip
+IC_CHECK=checkbox					#newip success
+IC_ERROR=error						#wrong arguments, login error
+IC_REMOVE=gtk-remove				#remove configuration
 
-########################################
-#            INITALIZATION             #
-########################################
+#########################################
+#			INITALIZATION
+#########################################
 # be sure to use the GUI mode if requested
 if [[ ! -z "`echo "$@" | grep "\-g"`"  ]]; then
-    GUI=true
+	GUI=true
 elif [[ ! -z `which figlet 2> /dev/null` ]]; then
-        echo "Netty Gear" | figlet
-        echo ""
+		echo "Netty Gear" | figlet
+		echo ""
 fi
 
 # 0 parameters?
 if [[ $# == 0 ]]; then
-    showHelp
-    exit 0
+	showHelp
+	exit 0
 fi
 
 # too many?
 if [[ "$GUI" == "true" && $# > 2  || ! "$GUI" == "true" && $# > 1 ]]; then
-    notify $IC_ERROR "Too many arguments"
-    exit 1
+	notify $IC_ERROR "Too many arguments"
+	exit 1
 fi
 
 
@@ -229,77 +229,77 @@ LOGIN=`curl -s -u $U:$P $HOST`
 LOGIN=`curl -s -u $U:$P $HOST`
 
 if [[ -z "$LOGIN" ]]; then
-    notify $IC_ERROR "Login:" "Network is Down"
-    exit 2
+	notify $IC_ERROR "Login:" "Network is Down"
+	exit 2
 else
-    CHECK="Another Administrator online"
-    ANSWER=`echo "$LOGIN" | grep -c "$CHECK"`
-    if (( $ANSWER == 1 )); then
-        notify $IC_ERROR "Login:" "$CHECK"
-        exit 3
-    fi
-    CHECK="Authorization warning"
-    ANSWER=`echo "$LOGIN" | grep -c "$CHECK"`
-    if (( $ANSWER == 1 )); then
-        notify $IC_ERROR "Login:" "$CHECK"
-        clearConfiguration
-        exit 4
-    fi
+	CHECK="Another Administrator online"
+	ANSWER=`echo "$LOGIN" | grep -c "$CHECK"`
+	if (( $ANSWER == 1 )); then
+		notify $IC_ERROR "Login:" "$CHECK"
+		exit 3
+	fi
+	CHECK="Authorization warning"
+	ANSWER=`echo "$LOGIN" | grep -c "$CHECK"`
+	if (( $ANSWER == 1 )); then
+		notify $IC_ERROR "Login:" "$CHECK"
+		clearConfiguration
+		exit 4
+	fi
 fi
 
 
-########################################
-#               COMMANDS               #
-########################################
+#########################################
+#				COMMANDS
+#########################################
 
 # letter surronded by : require an argument
 while getopts "ghlrindac" opt; do
-    case "$opt" in
-      g)
-        ;;
-      h)                    #help
-        showHelp
-        exit 0
-        ;;
-      l)                    #list [force GUI=true, selection mode with zenity]
-        showListGUI
-        exit 0
-        ;;
-      r)                    #reboot
-        rebootRouter
-        exit 0
-        ;;
-      i)                    #show net IP
-        showIP
-        exit 0
-        ;;
-      n)                    #new IP
-        newIP
-        exit 0
-        ;;
-      d)                    #show DL speed
-        showDLspeed
-        exit 0
-        ;;
-      a)                    #set username & password
-        setAuthentication  "force"
-        ;;
-      c)                    #clear configuration
-        clearConfiguration
-        ;;
-      \?)
-        echo "Invalid option: -$OPTARG" >&2
-        exit 1
-        ;;
-      :)
-        echo "Option -$OPTARG requires an argument." >&2
-        exit 1
-        ;;
-      *)
-         showHelp
-         break
-         ;;
-    esac
+	case "$opt" in
+	  g)
+		;;
+	  h)					#help
+		showHelp
+		exit 0
+		;;
+	  l)					#list [force GUI=true, selection mode with zenity]
+		showListGUI
+		exit 0
+		;;
+	  r)					#reboot
+		rebootRouter
+		exit 0
+		;;
+	  i)					#show net IP
+		showIP
+		exit 0
+		;;
+	  n)					#new IP
+		newIP
+		exit 0
+		;;
+	  d)					#show DL speed
+		showDLspeed
+		exit 0
+		;;
+	  a)					#set username & password
+		setAuthentication  "force"
+		;;
+	  c)					#clear configuration
+		clearConfiguration
+		;;
+	  \?)
+		echo "Invalid option: -$OPTARG" >&2
+		exit 1
+		;;
+	  :)
+		echo "Option -$OPTARG requires an argument." >&2
+		exit 1
+		;;
+	  *)
+		 showHelp
+		 break
+		 ;;
+	esac
 done
 
 exit 0
diff --git a/video-converter/video-converter b/video-converter/video-converter
--- a/video-converter/video-converter
+++ b/video-converter/video-converter
@@ -18,115 +18,115 @@ INPUT="$1"
 
 EXEC=`which avconv 2> /dev/null`
 if [ -z "$EXEC" ]; then
-    EXEC=`which ffmpeg` 
+	EXEC=`which ffmpeg` 
 
-    if [ -z "$EXEC" ]; then
-       echo "avconv | ffmpeg not found"
-       exit 0
-    fi
+	if [ -z "$EXEC" ]; then
+	   echo "avconv | ffmpeg not found"
+	   exit 0
+	fi
 fi
 
 while [ $? == 0 ]; do
-    # open file
-    if [[ ! -z "$INPUT" ]]; then
-        if [[ ! -f "$INPUT" ]]; then
-            echo "File does not exsist"
-            exit
-        fi
-    else 
-        INPUT=`yad --file --title="Video Converter" --name="Video Converter" --center --on-top \
-            --width=640 --height=480 \
-            --window-icon=$ICON \
-            --file-filter='Videos | *.mp4 *.mkv *.avi *.flv *.webm *.m4v *.mov *.ogg *.mpeg *.matroska *.asf *.wmv' \
-            --file-filter='*.avi | *.avi' \
-            --file-filter='*.asf | *.asf' \
-            --file-filter='*.flv | *.flv' \
-            --file-filter='*.m4v | *.m4v' \
-            --file-filter='*.matroska | *.matroska' \
-            --file-filter='*.mkv | *.mkv' \
-            --file-filter='*.mov | *.mov' \
-            --file-filter='*.mp4 | *.mp4' \
-            --file-filter='*.mpeg | *.mpeg' \
-            --file-filter='*.ogg | *.ogg' \
-            --file-filter='*.webm | *.webm' \
-            --file-filter='*.wmv | *.wmv' `
-    fi
+	# open file
+	if [[ ! -z "$INPUT" ]]; then
+		if [[ ! -f "$INPUT" ]]; then
+			echo "File does not exsist"
+			exit
+		fi
+	else 
+		INPUT=`yad --file --title="Video Converter" --name="Video Converter" --center --on-top \
+			--width=640 --height=480 \
+			--window-icon=$ICON \
+			--file-filter='Videos | *.mp4 *.mkv *.avi *.flv *.webm *.m4v *.mov *.ogg *.mpeg *.matroska *.asf *.wmv' \
+			--file-filter='*.avi | *.avi' \
+			--file-filter='*.asf | *.asf' \
+			--file-filter='*.flv | *.flv' \
+			--file-filter='*.m4v | *.m4v' \
+			--file-filter='*.matroska | *.matroska' \
+			--file-filter='*.mkv | *.mkv' \
+			--file-filter='*.mov | *.mov' \
+			--file-filter='*.mp4 | *.mp4' \
+			--file-filter='*.mpeg | *.mpeg' \
+			--file-filter='*.ogg | *.ogg' \
+			--file-filter='*.webm | *.webm' \
+			--file-filter='*.wmv | *.wmv' `
+	fi
 
-    # split input to {path/name,  extension}
-    FORMAT="mp4 mkv avi flv webm m4v mov ogg mpeg matroska asf wmv"
-    EXT=($FORMAT)
-    for EXT in "${EXT[@]}"
-    do
-        if [[ "$INPUT" =~ .$EXT ]]; then
-            PATHNAME=`echo "$INPUT" | sed s/.$EXT//g `
-            break;
-        fi
-    done
+	# split input to {path/name,  extension}
+	FORMAT="mp4 mkv avi flv webm m4v mov ogg mpeg matroska asf wmv"
+	EXT=($FORMAT)
+	for EXT in "${EXT[@]}"
+	do
+		if [[ "$INPUT" =~ .$EXT ]]; then
+			PATHNAME=`echo "$INPUT" | sed s/.$EXT//g `
+			break;
+		fi
+	done
 
-    if [[ -z "$PATHNAME" ]]; then
-        echo "Not a video file"
-        exit
-    fi
+	if [[ -z "$PATHNAME" ]]; then
+		echo "Not a video file"
+		exit
+	fi
 
-    # split path/name to {name, dir}
-    #num=`echo "$INPUT" | grep -o "/" | wc -l`
-    #NAME=`echo "$PATHNAME" | cut -d '/' -f $(($num+1))`
-    #DIR=`echo "$PATHNAME" | sed s/."$NAME"//g`
+	# split path/name to {name, dir}
+	#num=`echo "$INPUT" | grep -o "/" | wc -l`
+	#NAME=`echo "$PATHNAME" | cut -d '/' -f $(($num+1))`
+	#DIR=`echo "$PATHNAME" | sed s/."$NAME"//g`
 
-    # forms parameters
-    CODEC_VID="hevc libx264 libxvid libtheora mpeg4 flv"
-    CODEC_AUD="libmp3lame libvorbis vorbis aac ac3 flac"
-    BIT_VID="512 16..65536 32"
-    BIT_AUD="192 16..1536 32"
-    # TODO: remove this line. I should put a check for same directory\same extension output
-    # I should add a destination folder field in the form or add a question with a combobox
-    FORMAT=`echo "$FORMAT" | sed s/"$EXT"//g `; FORMAT=`echo ${FORMAT}`
+	# forms parameters
+	CODEC_VID="hevc libx264 libxvid libtheora mpeg4 flv"
+	CODEC_AUD="libmp3lame libvorbis vorbis aac ac3 flac"
+	BIT_VID="512 16..65536 32"
+	BIT_AUD="192 16..1536 32"
+	# TODO: remove this line. I should put a check for same directory\same extension output
+	# I should add a destination folder field in the form or add a question with a combobox
+	FORMAT=`echo "$FORMAT" | sed s/"$EXT"//g `; FORMAT=`echo ${FORMAT}`
 
-    PARAMS=`yad --form --title="Video Converter" --center --on-top --window-icon=$ICON \
-        --field="Codec Video":CBE "$CODEC_VID" \
-        --field="Codec Audio":CBE "$CODEC_AUD" \
-        --field="Skip Audio Transcoding":CHK TRUE \
-        --field="BitRate Video":NUM "$BIT_VID" \
-        --field="BitRate Audio":NUM "$BIT_AUD" \
-        --field="Format":CB "$FORMAT" \
-        --columns=2 \
-        --item-separator=' ' `
+	PARAMS=`yad --form --title="Video Converter" --center --on-top --window-icon=$ICON \
+		--field="Codec Video":CBE "$CODEC_VID" \
+		--field="Codec Audio":CBE "$CODEC_AUD" \
+		--field="Skip Audio Transcoding":CHK TRUE \
+		--field="BitRate Video":NUM "$BIT_VID" \
+		--field="BitRate Audio":NUM "$BIT_AUD" \
+		--field="Format":CB "$FORMAT" \
+		--columns=2 \
+		--item-separator=' ' `
 
-    if [ $? != 0 ] ; then
-        break
-    fi
+	if [ $? != 0 ] ; then
+		break
+	fi
 
-    CODEC_VID=`echo $PARAMS | cut -d '|' -f 1`
-    CODEC_AUD=`echo $PARAMS | cut -d '|' -f 2`
-    SKIP_AUD=`echo $PARAMS | cut -d '|' -f 3`
-    BIT_VID=`echo $PARAMS | cut -d '|' -f 4 | cut -d ',' -f 1`
-    BIT_AUD=`echo $PARAMS | cut -d '|' -f 5 | cut -d ',' -f 1`
-    FORMAT=`echo $PARAMS | cut -d '|' -f 6`
+	CODEC_VID=`echo $PARAMS | cut -d '|' -f 1`
+	CODEC_AUD=`echo $PARAMS | cut -d '|' -f 2`
+	SKIP_AUD=`echo $PARAMS | cut -d '|' -f 3`
+	BIT_VID=`echo $PARAMS | cut -d '|' -f 4 | cut -d ',' -f 1`
+	BIT_AUD=`echo $PARAMS | cut -d '|' -f 5 | cut -d ',' -f 1`
+	FORMAT=`echo $PARAMS | cut -d '|' -f 6`
 
-    # fix syntax for avconv
-    VIDEO="-c:v $CODEC_VID -b:v "$BIT_VID"k"
-    if [[ $SKIP_AUD == "TRUE" ]] ; then
-            AUDIO="-c:a copy"
-        else
-            AUDIO="-c:a $CODEC_AUD -b:a "$BIT_AUD"k"
-    fi
+	# fix syntax for avconv
+	VIDEO="-c:v $CODEC_VID -b:v "$BIT_VID"k"
+	if [[ $SKIP_AUD == "TRUE" ]] ; then
+			AUDIO="-c:a copy"
+		else
+			AUDIO="-c:a $CODEC_AUD -b:a "$BIT_AUD"k"
+	fi
 
-    # fix mkv format for avconv
-    EXT_OUT=$FORMAT
-    if [[ $FORMAT == "mkv" ]]; then
-        FORMAT="matroska"
-    fi
+	# fix mkv format for avconv
+	EXT_OUT=$FORMAT
+	if [[ $FORMAT == "mkv" ]]; then
+		FORMAT="matroska"
+	fi
 
-    # convert video
-    $EXEC -i "$INPUT" -f $FORMAT $VIDEO $AUDIO "$PATHNAME".$EXT_OUT
+	# convert video
+	$EXEC -i "$INPUT" -f $FORMAT $VIDEO $AUDIO "$PATHNAME".$EXT_OUT
 
-    # TODO: ask if I want to play the file(to check it) and then ask to remove the old one
-    notify-send -i $ICON "Converted: $PATHNAME.$EXT_OUT"
+	# TODO: ask if I want to play the file(to check it) and then ask to remove the old one
+	notify-send -i $ICON "Converted: $PATHNAME.$EXT_OUT"
 
-    #reset input
-    INPUT=""
+	#reset input
+	INPUT=""
 
-    yad   --image "dialog-question" --title "Alert" --center --on-top --window-icon=$ICON \
-                 --text "Convert another one?" \
-                 --button=yes --button=no
+	yad   --image "dialog-question" --title "Alert" --center --on-top --window-icon=$ICON \
+				 --text "Convert another one?" \
+				 --button=yes --button=no
 done
